name: "build"

on:
  push:
    branches:
      - main
      - 7.x
      - 8.x
    tags:
      - "*"
  pull_request:
    branches:
      - main
      - 7.x
      - 8.x

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.19"
      - name: Setup Elasticsearch / Kibana
        run: |
          set -e
          docker-compose up elasticsearch &
          echo "Waiting for Elasticsearch availability"
          until curl -s http://localhost:9200 | grep -q 'missing authentication credentials'; do sleep 30; done;
          echo "Setting kibana_system password"
          until curl -s -X POST -u elastic:changeme -H "Content-Type: application/json" http://localhost:9200/_security/user/kibana_system/_password -d "{\"password\":\"changeme\"}" | grep -q "^{}"; do sleep 10; done
          curl -XPOST -u elastic:changeme http://localhost:9200/_license/start_trial?acknowledge=true
          docker-compose up kibana &
          sleep 30
      - name: Run build
        run: make build
      - name: Run acceptance tests
        run: KIBANA_URL="http://localhost:5601" KIBANA_USERNAME="elastic" KIBANA_PASSWORD="changeme" make testacc
      - uses: codecov/codecov-action@v2
        with:
          files: coverage.out
          flags: unittests
          fail_ci_if_error: true

  goreleaser:
    runs-on: ubuntu-latest
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Import GPG key
        id: import_gpg
        uses: paultyng/ghaction-import-gpg@v2.1.0
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
